### ISSUE TITLE
Task: FileEvent Model is not compatible with Sigma file-event rules

### ISSUE THREAD

**Issue by hongsam14** [enki-polvo/polvo-logger#9]
## Current Behavior

file's abspath is named as `Path` in `FileMetadata` Model

```go
type FileMetadata struct {
	// process relation
	PID int64 `json:"Pid"` // example: 1234
	UID int64 `json:"Uid"` // example: 1000
	// file info
	Path string `json:"Path"` // example: "/tmp/file.txt"
	// file operation
	Op   state.FileOp `json:"Op"`   // example: "READ" "RENAME" "WRITE" etc..
	Mode uint64       `json:"Mode"` // example: 0
}
```
However, the field name `Path` is not compatible with `TargetFilename` in sigma rule's detection condition

```yaml
detection:
    selection1:
        TargetFilename|startswith:
            - '/etc/cron.d/'
    selection2:
        TargetFilename|contains:
            - '/etc/cron.allow'
    condition: 1 of selection*
```

## Expected Behavior

change field name `Path` to `TargetFilename`
